color:
  buoy:
    red:
      lab_low: [0, 150, 135]
      lab_high: [255, 205, 185]

    green:
      lab_low: [0, 70, 130]
      lab_high: [255, 120, 175]

    yellow:
      lab_low: [0, 82, 145]
      lab_high: [255, 148, 205]

  channel_marker:
    hsv_low: [17.3988, 17.697, 223.125]
    hsv_high: [42.2619, 255.0, 255.0]
