color:
  buoy:
    red:
      lab_low: [0, 160, 140]
      lab_high: [255, 210, 188]

    green:
      lab_low: [0, 90, 135]
      lab_high: [255, 120, 160]

    yellow:
      lab_low: [0, 95, 150]
      lab_high: [255, 160, 220]

  channel_marker:
    hsv_low: [17.3988, 17.697, 223.125]
    hsv_high: [42.2619, 255.0, 255.0]
