# Always prefer bgr to hsv when red is a possible color
color:
  buoy:
    red:
      LAB: [[0, 160, 148], [255, 190, 170]]

    green:
      LAB: [[0, 63, 170], [255, 90, 190]]

    yellow:
      LAB: [[0, 97, 160], [255, 115, 200]]

  path_marker:
      HSV: [[11, 0, 0], [13, 255, 255]]
