# Always prefer bgr to hsv when red is a possible color
color:
  buoy:
    red:
      bgr_low: [0.0, 0.0, 49.572]
      bgr_high: [56.661, 46.053, 201.8835]

    yellow:
      bgr_low: [0.0, 70.839, 70.839]
      bgr_high: [24.786, 201.8835, 208.947]

    green:
      bgr_low: [0.0, 81.447, 3.5445]
      bgr_high: [38.964, 198.339, 46.053]
