# Always prefer bgr to hsv when red is a possible color
color:
  buoy:
    red:
      lab_low: [0, 160, 148]
      lab_high: [255, 190, 170]

    green:
      lab_low: [0, 63, 170]
      lab_high: [255, 90, 190]

    yellow:
      lab_low: [0, 100, 172]
      lab_high: [255, 115, 200]

  channel_marker:
    hsv_low: [0.0, 0.0, 50.0]
    hsv_high: [83.3782, 255.0, 255.0]
