accel_feedforward: 0, 0, 0, 0, 0, 0
alpha: 0, 0, 0.1, 0.1, 0.1, 0
beta: 0, 0, 0, 0, 0, 0
k: 1.3, 1.3, 1.0, 1.3, 1.3, 1.0
ks: 400, 400, 600, 70, 70, 70
state: true
two_d_mode: false
use_rise: true
vel_feedforward: 0, 0, 0, 0, 0, 0
